### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by Robdel12** [thefrontside/emberx-select-blockless#2]
We should incorporate @gte451f's changes outlined here:

https://github.com/thefrontside/emberx-select/pull/63

(Note @gte451f if you want the commit credit here I'm totally okay with you reopening a PR on this repo :+1: )

**Comment by gte451f** [comment]
Wow, I did not realize there was a blockless version of the project.  Will send PR to this one instead.  Will Blockless compatibility be phased out in the future?

**Comment by Robdel12** [comment]
We just broke it out into it's own addon recently. This one has yet to be published (waiting to release x-select 2.0 today or tomorrow) but it should be supported as long as it needs to be.

**Comment by Robdel12** [comment]
This was fixed in #3
